[package]
name = "network-messages"
version = "0.1.0"
edition = "2024"
description = "An example for netvy showcasing how to use network messages"
documentation = "https://github.com/invertedEcho/netvy"
homepage = "https://github.com/invertedEcho/netvy"
repository = "https://github.com/invertedEcho/netvy"
license-file = "../../LICENSE"
keywords = ["bevy", "gamdev", "multiplayer", "networking"]
publish = false

[dependencies]
bevy = { workspace = true, default-features = true }
netvy = { path = "../../crates/plugin/", version = "0.3.0" }
serde = { workspace = true }
