[package]
name = "netvy"
version = "0.2.0"
edition = "2024"
description = " A multiplayer framework for the bevy game engine"
documentation = "https://github.com/invertedEcho/netvy"
homepage = "https://github.com/invertedEcho/netvy"
repository = "https://github.com/invertedEcho/netvy"
license-file = "../../LICENSE"
keywords = ["bevy", "gamdev", "multiplayer", "networking"]
categories = ["game-development"]

[dependencies]
bevy = { workspace = true, default-features = false, features = [
  "bevy_log",
  "debug"
] }
bincode = { workspace = true, features = ["serde"] }
serde = { workspace = true }
